import pandas as pd
import matplotlib.pyplot as plt

# --- load the CSV generated by the simulation ---
df = pd.read_csv('sipm_hits.csv')

# --- quick summary: total photons per SiPM aggregated over all events ---
bin_cols = [c for c in df.columns if c.startswith('bin')]
sipm_tot = df.groupby('sipmID')[bin_cols].sum().sum(axis=1)

plt.figure(figsize=(10, 4))
plt.bar(sipm_tot.index, sipm_tot.values)
plt.xlabel('SiPM ID')
plt.ylabel('Total photons detected')
plt.title('Aggregate photon count per SiPM (all events)')
plt.tight_layout()
plt.show()

# --- heat‑map: time‑bin distribution for FIRST event only (eventID=0) ---
evt0 = df[df.eventID == 0].set_index('sipmID')[bin_cols].sort_index()

plt.figure(figsize=(8, 6))
plt.imshow(evt0, aspect='auto', interpolation='nearest')
plt.colorbar(label='photons / 16 ns bin')
plt.xlabel('Time bin (0 = 0‑16 ns … 12 = 192‑208 ns)')
plt.ylabel('SiPM ID')
plt.title('Event 0: time‑binned photons per SiPM')
plt.tight_layout()
plt.show()
